---
# handlers file for nfs_server
- name: Reload nfs
  become: true
  ansible.builtin.command:
    cmd: 'exportfs -ra'
  changed_when: true

- name: Restart firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: restarted
    enabled: true
